name: scd_env

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pysheds
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - joblib
  - numba
  - networkx
  - pytorch
  - torchvision
  - pip
  - pip:
      - scienceplots
      - opencv-python-headless