name: IRP
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
  - pytorch
  - sepandhaghighi
dependencies:
  - _python_abi3_support=1.0
  - affine=2.4.0
  - aom=3.13.2
  - appnope=0.1.4
  - argcomplete=3.6.3
  - arrow-cpp=23.0.1
  - asttokens=3.0.1
  - attrs=26.1.0
  - aws-c-auth=0.10.1
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.2
  - aws-c-event-stream=0.6.0
  - aws-c-http=0.10.12
  - aws-c-io=0.26.3
  - aws-c-mqtt=0.15.2
  - aws-c-s3=0.11.5
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.10
  - aws-crt-cpp=0.37.4
  - aws-sdk-cpp=1.11.774
  - backports.zstd=1.5.0
  - blas=1.0
  - blosc=1.21.6
  - bokeh=3.9.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cartopy=0.25.0
  - cdsapi=0.7.7
  - cfgv=3.5.0
  - charset-normalizer=3.4.7
  - click-plugins=1.1.1.2
  - cloudpickle=3.1.2
  - comm=0.2.3
  - configobj=5.0.9
  - contourpy=1.3.3
  - cpython=3.13.13
  - cvxopt=1.3.3
  - cycler=0.12.1
  - cytoolz=1.1.0
  - dask=2026.3.0
  - dask-core=2026.3.0
  - dask-jobqueue=0.9.0
  - dav1d=1.5.3
  - debugpy=1.8.20
  - decorator=5.2.1
  - distlib=0.4.1
  - distributed=2026.3.0
  - donfig=0.8.1.post1
  - dsdp=5.8
  - eccodes=2.46.0
  - ecmwf-datastores-client=0.5.1
  - executing=2.2.1
  - fftw=3.3.11
  - filelock=3.29.0
  - fontconfig=2.17.1
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - fsspec=2026.4.0
  - gdal=3.12.4
  - geos=3.10.6
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - h2=4.3.0
  - h5py=3.16.0
  - harfbuzz=12.3.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.3
  - identify=2.6.19
  - imageio=2.37.3
  - importlib-metadata=9.0.0
  - ipykernel=7.2.0
  - ipython=9.12.0
  - ipython_pygments_lexers=1.1.1
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - jpeg=9f
  - json-c=0.18
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.5.0
  - krb5=1.22.2
  - lazy_loader=0.5
  - lcms2=2.19
  - lerc=4.1.0
  - libabseil=20260107.1
  - libaec=1.1.5
  - libamd=3.3.3
  - libarchive=3.8.7
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libcolamd=3.3.4
  - libcurl=8.19.0
  - libcxsparse=4.4.1
  - libcxx=22.1.2
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.5
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.12.4
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libgrpc=1.78.1
  - libhwloc=2.13.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libklu=2.3.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm20=20.1.8
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libnetcdf=4.10.0
  - libnghttp2=1.68.1
  - libopenblas=0.3.31
  - libopenjpeg=2.5.4
  - libparu=1.0.0
  - libpng=1.6.56
  - libprotobuf=6.33.5
  - librbio=4.3.4
  - libre2-11=2025.11.05
  - libsodium=1.0.21
  - libspatialite=5.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.52.0
  - libssh2=1.11.1
  - libsuitesparseconfig=7.10.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.14.6
  - libxml2-16=2.14.6
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.2
  - llvm-openmp=20.1.8
  - llvmlite=0.47.0
  - locket=1.0.0
  - looseversion=1.3.0
  - lxml=6.0.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=4.2.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdurl=0.1.2
  - metis=5.1.0
  - minizip=4.0.10
  - mintpy=1.6.3
  - mpfr=4.2.2
  - msgpack-python=1.1.2
  - multiurl=0.3.7
  - munkres=1.1.4
  - narwhals=2.22.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nodeenv=1.10.0
  - numba=0.65.1
  - numpy=2.4.4
  - numpy-base=2.4.4
  - openssl=3.6.3
  - orc=2.2.0
  - packaging=26.0
  - parso=0.8.6
  - partd=1.4.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pillow=12.2.0
  - pip=26.0.1
  - pixman=0.46.4
  - platformdirs=4.9.6
  - pre-commit=4.6.0
  - proj=9.7.1
  - prompt-toolkit=3.0.52
  - protobuf=6.33.5
  - psutil=7.2.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyaps3=0.3.7
  - pyarrow=23.0.1
  - pycparser=3.0
  - pygments=2.20.0
  - pygrib=2.1.8
  - pykdtree=1.4.3
  - pykml=0.2.0
  - pyparsing=3.3.2
  - pyproj=3.7.2
  - pyresample=1.35.0
  - pysheds=0.5
  - pyshp=3.0.9
  - pysocks=1.7.1
  - pysolid=0.3.4
  - python=3.13.12
  - python-dateutil=2.9.0.post0
  - python-discovery=1.4.0
  - python-gil=3.13.13
  - python_abi=3.13
  - pytz=2026.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - rasterio=1.5.0
  - re2=2025.11.05
  - readline=8.3
  - rich=15.0.0
  - richdem=2.4.0
  - scikit-image=0.26.0
  - scipy=1.17.1
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.51.2
  - stack_data=0.6.3
  - suitesparse=7.10.1
  - tbb=2023.0.0
  - tblib=3.2.2
  - tifffile=2026.3.3
  - tk=8.6.15
  - toolz=1.1.0
  - tornado=6.5.5
  - tqdm=4.67.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2026a
  - ukkonen=1.1.0
  - uriparser=0.9.8
  - utf8proc=2.6.1
  - utm=0.7.0
  - virtualenv=21.4.2
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2026.3.0
  - xz=5.8.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=4.1.0
  - zlib=1.3.2
  - zstd=1.5.7
  - pip:
      - asciitree==0.3.3
      - beautifulsoup4==4.14.3
      - blessings==1.7
      - certifi==2026.2.25
      - cffi==2.0.0
      - click==8.3.2
      - cligj==0.7.2
      - cryptography==46.0.7
      - earthengine-api==1.7.21
      - ee==0.2
      - esda==2.9.0
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - fonttools==4.62.1
      - geojson==3.2.0
      - geopandas==1.1.3
      - geotiff==0.2.10
      - google-api-core==2.30.3
      - google-api-python-client==2.194.0
      - google-auth==2.49.2
      - google-auth-httplib2==0.3.1
      - google-cloud-core==2.5.1
      - google-cloud-storage==3.10.1
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.2
      - googleapis-common-protos==1.74.0
      - httplib2==0.31.2
      - idna==3.11
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - libpysal==4.14.1
      - mpmath==1.3.0
      - nbformat==5.10.4
      - numcodecs==0.16.5
      - opencv-python==5.0.0.93
      - pandas==3.0.2
      - plotly==6.8.0
      - pointpats==2.5.5
      - proto-plus==1.27.2
      - pyasn1==0.6.3
      - pyasn1-modules==0.4.2
      - pyogrio==0.12.1
      - referencing==0.37.0
      - requests==2.33.1
      - rpds-py==2026.5.1
      - scienceplots==2.2.1
      - scikit-learn==1.8.0
      - seaborn==0.13.2
      - setuptools==81.0.0
      - soupsieve==2.8.4
      - structure-tensor==0.3.4
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.12.0
      - torchsummary==1.5.1
      - torchvision==0.27.0
      - uritemplate==4.2.0
      - urllib3==2.6.3
      - zarr==2.12.0
